### ISSUE TITLE
ModuleNotFoundError: No module named 'yolact_interface'

### ISSUE THREAD

**Issue by jacques-saraydaryan** [Geonhee-LEE/yolact_ros#2]
I successfully installed all requirements but i didn't find any python module yolact_interface in your code, leading to the following error when running:
rosrun yolact_ros yolact_ros.py  --trained_model=../weights/yolact_resnet50_54_800000.pth  --score_threshold=0.3 --top_k=100 --video_multiframe=2 --video=0

Traceback (most recent call last):
  File ".../yolact_ros/script/yolact_ros.py", line 30, in <module>
    from yolact_interface import YolactInterface
ModuleNotFoundError: No module named 'yolact_interface'

**Comment by Sushant-Chavan** [comment]
@Geonhee-LEE Thanks for sharing the code. I am also facing the same issue. Could you please shed some light on how to fix this? Thanks in advance!

**Comment by Geonhee-LEE** [comment]
@jacques-saraydaryan  @Sushant-Chavan  Hello,
Thanks for interesting this repo.
the file 'yolact_ros.py' you mentioned is older version.. so it is changed the class and functions.
Why don't you run other files such as 'yolact_capture_img.py'
